/**
 * Created by lupan on 2017/1/25.
 */
var json = {
    "moduleinfo": {
        "activity_count": [{"count": 1, "count_phone": 1}],
        "partner_count": [{"count": 1, "count_phone": 1}],
        "product_count": [{"count": 1, "count_phone": 1}],
        "solution_count": [{"count": 1, "count_phone": 1}],
        "market_count": [{"count": 1, "count_phone": 1}],
        "data_count": [{"count": 1, "count_phone": 1}],
        "community_count": [{"count": 1, "count_phone": 1}],
        "support_count": [{"count": 1, "count_phone": 1}],
        "more_count": [{"count": 1, "count_phone": 1}],
        "tpl1_count": [{"count": 2, "count_phone": 2}],
        "tpl2_count": [{"count": 3, "count_phone": 3}],
        "tpl3_count": [{"count": 4, "count_phone": 4}],
        "tpl4_count": [{"count": 1, "count_phone": 1}],
        "tpl5_count": [{"count": 2, "count_phone": 2}],
        "tpl6_count": [{"count": 1, "count_phone": 1}]
    },
    "tpl6": [{
        "items": [{
            "text": "行业解决方案",
            "items": [{
                "tabLink3": "https://www.aliyun.com/solution/ecommerce/imagesearch",
                "tabText1": "大数据运营",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/ecommerce/https",
                "p": "快速搭建新零售平台，支持秒杀、视频直播等业务",
                "link": "https://www.aliyun.com/solution/ecommerce",
                "tabLink1": "https://www.aliyun.com/solution/ecommerce/dataoperation",
                "spm": "dataoperation",
                "tips": "none",
                "tabText3": "以图搜图",
                "tabText2": "全站HTTPS",
                "h3": "新零售解决方案"
            }, {
                "tabLink3": "https://www.aliyun.com/solution/game/mmoprg.html",
                "tabText1": "MMO",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/game/moba.html",
                "p": "为手游/页游/端游开发者提供部署方案助力成长满足互联网金融/证券/银行/保险业务需求",
                "link": "https://www.aliyun.com/solution/game",
                "tabLink1": "https://www.aliyun.com/solution/game/mmo.html",
                "spm": "game",
                "tips": "none",
                "tabText3": "MMORPG页游",
                "tabText2": "MOBA",
                "h3": "大游戏解决方案"
            }, {
                "tabLink3": "https://www.aliyun.com/solution/estate/smartpark",
                "tabText1": "大数据营销",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/estate/decision",
                "p": "房地产+互联网大数据，助力房地产行业无限创新",
                "link": "https://www.aliyun.com/solution/estate",
                "tabLink1": "https://www.aliyun.com/solution/estate/exact-marketing",
                "spm": "estatesolution",
                "tips": "new",
                "tabText3": "智能停车场",
                "tabText2": "土地投资决策",
                "h3": "房地产解决方案"
            }, {
                "tabLink3": "https://www.aliyun.com/solution/finance/securitieszx",
                "tabText1": "互联网金融",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/finance/insuranceds",
                "p": "满足互联网金融/证券/银行/保险业务需求",
                "link": "https://www.aliyun.com/solution/finance",
                "tabLink1": "https://www.aliyun.com/solution/finance/p2p.html",
                "spm": "finance",
                "tips": "none",
                "tabText3": "金融交易所上云",
                "tabText2": "保险核心上云",
                "h3": "新金融解决方案"
            }, {
                "tabLink3": "https://www.aliyun.com/solution/govcloud/vod.html",
                "tabText1": "智慧交通大数据",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/govcloud/revenue.html",
                "p": "满足政府/交通/公安/税务局等业务需求",
                "link": "https://www.aliyun.com/solution/govcloud",
                "tabLink1": "https://www.aliyun.com/solution/govcloud/trafficbigdata.html",
                "spm": "govcloud",
                "tips": "new",
                "tabText3": "市民交通违法举报",
                "tabText2": "电子税务局",
                "h3": "大政务解决方案"
            }, {
                "tabLink3": "https://www.aliyun.com/solution/media/video",
                "tabText1": "智能监控",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/media/live",
                "p": "一站式提供“海量存储、高效分发、极速网络”等强大服务",
                "link": "https://www.aliyun.com/solution/media",
                "tabLink1": "https://www.aliyun.com/solution/media/monitor",
                "spm": "media",
                "tips": "none",
                "tabText3": "视频点播",
                "tabText2": "视频直播",
                "h3": "大视频解决方案"
            }, {
                "tabLink3": "https://www.aliyun.com/solution/energy/operation_car2",
                "tabText1": "分布式光伏",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/energy/rent_car",
                "p": "帮新运营商、服务商快速搭建标准化商业平台",
                "link": "https://www.aliyun.com/solution/energy",
                "tabLink1": "https://www.aliyun.com/solution/energy/gfy",
                "spm": "energy",
                "tips": "none",
                "tabText3": "充电桩运营",
                "tabText2": "电动汽车分时租赁",
                "h3": "新能源解决方案"
            }, {
                "tabLink3": "https://www.aliyun.com/solution/healthcare/remote.html",
                "tabText1": "互联网医疗",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/healthcare/image_cloud.html",
                "p": "集合传统医疗优势，致力构建智能医疗云生态",
                "link": "https://www.aliyun.com/solution/healthcare",
                "tabLink1": "https://www.aliyun.com/solution/healthcare/Medical.html",
                "spm": "healthcare",
                "tips": "new",
                "tabText3": "远程医疗",
                "tabText2": "影像云",
                "h3": "大健康解决方案"
            }, {
                "tabText1": "小型网站",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/web/normal.html?spm=5176.7996952.573293.2.DLGuBH",
                "p": "依据不同发展阶段，提供一站式建站方案",
                "link": "https://www.aliyun.com/solution/web",
                "tabLink1": "https://www.aliyun.com/solution/web/small.html?spm=5176.7996952.573293.1.DLGuBH",
                "spm": "websolution",
                "tips": "none",
                "tabText2": "中型网站",
                "h3": "网站解决方案"
            }, {
                "tabLink3": "https://www.aliyun.com/solution/industry/scada",
                "tabText1": "智能设备互联",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/industry/light",
                "p": "提供快速搭建一站式亿级设备接入、管理能力",
                "link": "https://www.aliyun.com/solution/industry",
                "tabLink1": "https://www.aliyun.com/solution/industry/equipment",
                "spm": "industry",
                "tips": "new",
                "tabText3": "工业控制scada",
                "tabText2": "光伏切片智能",
                "h3": "新制造解决方案"
            }, {
                "tabLink3": "https://www.aliyun.com/solution/transport/management.html",
                "tabText1": "商用车联网",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/iot/routing",
                "p": "利用物联网及大数据的技术优势， 助力运输企业降本增效",
                "link": "https://www.aliyun.com/solution/iot",
                "tabLink1": "https://www.aliyun.com/solution/iot/vehicle",
                "spm": "iot",
                "tips": "none",
                "tabText3": "运输管理",
                "tabText2": "路径优化",
                "h3": "大运输解决方案"
            }, {
                "tabLink3": "https://www.aliyun.com/solution/app/httpdns",
                "tabText1": "移动安全",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/app/speedup",
                "p": "轻松应对移动app爆发式增长",
                "link": "https://www.aliyun.com/solution/app",
                "tabLink1": "https://www.aliyun.com/solution/app/security",
                "spm": "appsolution",
                "tips": "none",
                "tabText3": "移动域名解析",
                "tabText2": "移动应用加速",
                "h3": "移动APP解决方案"
            }, {
                "tabText1": "容灾",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/hcloud",
                "p": "提供“海量存储、高效分发、极速网络”等服务",
                "link": "https://www.aliyun.com/solution/technology/new.html",
                "tabLink1": "https://www.aliyun.com/solution/recovery",
                "spm": "null",
                "tips": "none",
                "tabText2": "混合云",
                "h3": "新技术解决方案"
            }, {
                "tabLink3": "https://www.aliyun.com/solution/communication/live",
                "tabText1": "媒体公共云",
                "or": "true",
                "tabLink2": "https://www.aliyun.com/solution/communication/mediaprivate",
                "p": "基于高性能基础架构，提供面向媒体行业的快速新闻生产、节目制作、专业直播等业务场景",
                "link": "https://www.aliyun.com/solution/communication",
                "tabLink1": "https://www.aliyun.com/solution/communication/mediapublic",
                "spm": "communication",
                "tips": "none",
                "tabText3": "专业直播",
                "tabText2": "专有媒体云",
                "h3": "大传媒解决方案"
            }],
            "or": "false",
            "width": "1030px"
        }, {
            "text": "通用解决方案",
            "items": [{
                "or": "false",
                "p": "帮助客户向混合云架构平滑演进",
                "link": "https://www.aliyun.com/solution/dedicatedcloud",
                "spm": "zhuanyouyunsolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "专有云解决方案"
            }, {
                "or": "true",
                "p": "多层防护+云端大数据，提供整套安全产品和服务",
                "link": "https://www.aliyun.com/solution/security",
                "spm": "security",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "安全解决方案"
            }, {
                "or": "true",
                "p": "解决海量数据存档/备份、加工，加速分发等问题",
                "link": "https://www.aliyun.com/solution/storage",
                "spm": "storage",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云存储解决方案"
            }, {
                "or": "true",
                "p": "经历阿里巴巴电商考验，助企业快速构建分布式应用",
                "link": "https://www.aliyun.com/solution/middleware",
                "spm": "middleware",
                "tce_rule_count": "1",
                "tips": "new",
                "h3": "企业互联网架构方案"
            }, {
                "or": "false",
                "p": "帮助传统硬件负载均衡用户快速、平滑迁移到云平台",
                "link": "https://www.aliyun.com/solution/adn",
                "spm": "adn",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "应用交付网络解决方案"
            }, {
                "or": "true",
                "p": "高效高质输出运输方案，显著降低运输成本",
                "link": "https://data.aliyun.com/solution/dispatch",
                "spm": "dispatch",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "智能配送调度解决方案"
            }, {
                "or": "false",
                "p": "便捷3D模型导入、ET语音交互",
                "link": "https://data.aliyun.com/solution/vr",
                "spm": "vr",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "VR应用开发解决方案"
            }, {
                "or": "true",
                "p": "建立等保合规生态，提供一站式等保合规方案",
                "link": "https://www.aliyun.com/solution/classifiedprotection.html",
                "spm": "classifiedprotection",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "等级保护安全合规方案"
            }],
            "or": "false",
            "width": "700px"
        }, {
            "text": "大数据解决方案",
            "items": [{
                "or": "true",
                "p": "根据用户行为，推荐用户感兴趣的信息和商品",
                "link": "https://data.aliyun.com/solution/re",
                "spm": "re",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "个性化推荐"
            }, {
                "or": "true",
                "p": "提供从数据采集、存储加工、管理等数仓解决方案",
                "link": "https://data.aliyun.com/solution/base",
                "spm": "base",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "大数据仓库"
            }, {
                "or": "true",
                "p": "提供可跨异构数据存储系统、安全可靠低成本",
                "link": "https://data.aliyun.com/solution/cdp",
                "spm": "cdp",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云上数据集成方案"
            }, {
                "or": "false",
                "p": "提供从5min到未来1h精准度92%的路况拥堵预测",
                "link": "https://data.aliyun.com/solution/rp",
                "spm": "rp",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "路况预测"
            }, {
                "or": "true",
                "p": "判断台风未来的走向及汛情，帮助做出决策",
                "link": "https://data.aliyun.com/solution/tiqas",
                "spm": "tiqas",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "台风路径分析"
            }, {
                "or": "true",
                "p": "帮助您从无到有快速搭建自有营销推广系统",
                "link": "https://data.aliyun.com/solution/dm",
                "spm": "none",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "数字营销解决方案"
            }, {
                "or": "true",
                "p": "为工业客户提供基于人工智能的解决方案",
                "link": "https://data.aliyun.com/solution/industry",
                "spm": "industrydata",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "工业大数据服务解决方案"
            }, {
                "or": "true",
                "p": "多位交叉分析及智能算法",
                "link": "https://data.aliyun.com/solution/cds",
                "spm": "cds",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "企业数据服务解决方案"
            }],
            "or": "false",
            "width": "700px"
        }], "key": "solution"
    }],
    "partner": [{
        "text": "合作伙伴",
        "or": "false",
        "link": "https://partner.aliyun.com",
        "spm": "partner",
        "tips": "none"
    }],
    "activity": [{
        "text": "最新活动",
        "or": "false",
        "link": "https://www.aliyun.com/activity#/promotionArea",
        "spm": "activity",
        "tips": "hot"
    }],
    "product": [{
        "text": "产品",
        "level1": [{
            "text": "云计算基础服务",
            "or": "false",
            "tce_rule_count": "1",
            "key": "product_elastic",
            "tplType": "tpl1"
        }, {
            "text": "大数据（数加）",
            "or": "false",
            "link": "https://data.aliyun.com/product/product_index",
            "tce_rule_count": "1",
            "key": "product_database",
            "tplType": "tpl2"
        }, {
            "text": "安全（云盾）",
            "or": "false",
            "link": "https://www.aliyun.com/product/yundunall",
            "tce_rule_count": "1",
            "key": "product_yundun",
            "tplType": "tpl3"
        }, {
            "text": "域名与网站（万网）",
            "or": "false",
            "link": "https://wanwang.aliyun.com/",
            "tce_rule_count": "1",
            "key": "product_network",
            "tplType": "tpl4"
        }],
        "or": "false",
        "spm": "product",
        "tips": "none"
    }],
    "solution": [{
        "text": "解决方案",
        "or": "false",
        "link": "https://www.aliyun.com/solution/all",
        "spm": "solution",
        "tips": "none",
        "key": "solution",
        "tplType": "tpl6"
    }],
    "market": [{
        "text": "云市场",
        "or": "true",
        "link": "https://market.aliyun.com",
        "spm": "yunshichang2016",
        "tips": "none",
        "key": "market",
        "tplType": "tpl2"
    }],
    "data": [{"text": "大数据", "or": "false", "link": "https://data.aliyun.com", "spm": "dashuju", "tips": "none"}],
    "community": [{
        "text": "社区",
        "or": "true",
        "link": "https://yq.aliyun.com",
        "spm": "community",
        "tips": "none",
        "key": "community",
        "tplType": "tpl2"
    }],
    "support": [{
        "text": "支持",
        "or": "false",
        "link": "https://www.aliyun.com/support",
        "spm": "support",
        "tips": "none",
        "key": "support",
        "tplType": "tpl5"
    }],
    "more": [{
        "text": "更多",
        "level1": [{
            "text": "重要通道",
            "or": "false",
            "tce_rule_count": "1",
            "key": "more_passageway",
            "tplType": "tpl3"
        }, {
            "text": "教育与创业孵化",
            "or": "false",
            "tce_rule_count": "1",
            "key": "more_education",
            "tplType": "tpl3"
        }, {"text": "合作与生态", "or": "false", "tce_rule_count": "1", "key": "more_ecology", "tplType": "tpl3"}],
        "or": "false",
        "tips": "none"
    }],
    "tpl1": [{
        "items": [{
            "text": "弹性计算",
            "items": [{
                "or": "false",
                "p": "可弹性扩展、安全、稳定、易用的计算服务",
                "link": "https://www.aliyun.com/product/ecs",
                "spm": "yunfuwuqi",
                "tce_rule_count": "1",
                "h3": "云服务器 ECS"
            }, {
                "or": "false",
                "p": "可弹性扩展、高性能、高可靠的块级随机存储",
                "link": "https://www.aliyun.com/product/disk",
                "spm": "kuaicunchi",
                "tce_rule_count": "1",
                "h3": "块存储"
            }, {
                "or": "false",
                "p": "帮您轻松构建逻辑隔离的专有网络",
                "link": "https://www.aliyun.com/product/vpc",
                "spm": "zhuanyouVPC",
                "tce_rule_count": "1",
                "h3": "专有网络 VPC"
            }, {
                "or": "false",
                "p": "对多台云服务器进行流量分发的负载均衡服务",
                "link": "https://www.aliyun.com/product/slb",
                "spm": "fuzaijunh",
                "tce_rule_count": "1",
                "h3": "负载均衡"
            }, {
                "or": "false",
                "p": "自动调整弹性计算资源的管理服务",
                "link": "https://www.aliyun.com/product/ess",
                "spm": "tanxingshensou",
                "tce_rule_count": "1",
                "h3": "弹性伸缩"
            }, {
                "or": "false",
                "p": "批量创建、管理、配置云计算资源",
                "link": "https://www.aliyun.com/product/ros",
                "spm": "ziyuanpaibu",
                "tce_rule_count": "1",
                "h3": "资源编排"
            }, {
                "or": "false",
                "p": "应用全生命周期管理的 Docker 服务",
                "link": "https://www.aliyun.com/product/containerservice",
                "spm": "rongqifuwu",
                "tce_rule_count": "1",
                "h3": "容器服务"
            }, {
                "or": "false",
                "p": "加速深度学习、渲染和科学计算的 GPU 物理机",
                "link": "https://www.aliyun.com/product/hpc",
                "spm": "Hpcgaoxingn",
                "tce_rule_count": "1",
                "h3": "高性能计算 HPC"
            }, {
                "or": "false",
                "p": "简单易用的大规模并行批处理计算服务",
                "link": "https://www.aliyun.com/product/batchcompute",
                "spm": "piliangjisuan",
                "tce_rule_count": "1",
                "h3": "批量计算"
            }],
            "or": "false",
            "width": "700px",
            "spm": "tanxingjisuan",
            "tce_rule_count": "1"
        }, {
            "text": "数据库",
            "items": [{
                "or": "false",
                "p": "完全兼容MySQL，SQLServer，PostgreSQL",
                "link": "//www.aliyun.com/product/rds",
                "spm": "rds",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云数据库 RDS"
            }, {
                "or": "false",
                "p": "三节点副本集保证高可用",
                "link": "//www.aliyun.com/product/mongodb",
                "spm": "mongodb",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云数据库 MongoDB 版"
            }, {
                "or": "false",
                "p": "兼容开源 Redis 协议的 Key-Value 类型",
                "link": "//www.aliyun.com/product/kvstore",
                "spm": "kvstore",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云数据库 Redis 版"
            }, {
                "or": "false",
                "p": "在线缓存服务，为热点数据的访问提供高速响应",
                "link": "//www.aliyun.com/product/ocs",
                "spm": "ocs",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云数据库 Memcache 版"
            }, {
                "or": "false",
                "p": "支持 PB 级海量数据存储的分布式关系型数据库",
                "link": "//www.aliyun.com/product/petadata",
                "spm": "petadata",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "PB 级云数据库 PetaData （邀测中）"
            }, {
                "or": "false",
                "p": "基于Greenplum Database的MPP数据仓库",
                "link": "//www.aliyun.com/product/gpdb",
                "spm": "gpdb",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云数据库 HybridDB"
            }, {
                "or": "false",
                "p": "金融级高可靠、高性能、分布式自研数据库",
                "link": "//www.aliyun.com/product/oceanbase",
                "spm": "oceanbase",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云数据库 OceanBase（邀测中）"
            }, {
                "or": "false",
                "p": "比GoldenGate更易用，阿里异地多活基础架构",
                "link": "//www.aliyun.com/product/dts",
                "spm": "dts",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "数据传输"
            }, {
                "or": "false",
                "p": "比 phpMyAdmin 更强大，比 Navicat 更易用",
                "link": "//www.aliyun.com/product/dms",
                "spm": "dms",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "数据管理"
            }, {
                "or": "false",
                "p": "高并发、低延时、无限容量的Nosql数据存储服务",
                "link": "https://www.aliyun.com/product/ots",
                "spm": "ots2",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "表格存储"
            }],
            "or": "false",
            "link": "https://promotion.aliyun.com/ntms/product/apsaradb.html",
            "width": "700px",
            "spm": "datashujuku",
            "tce_rule_count": "1"
        }, {
            "text": "存储与CDN",
            "items": [{
                "or": "false",
                "p": "海量、安全和高可靠的云存储服务",
                "link": "//www.aliyun.com/product/oss",
                "spm": "oss",
                "tce_rule_count": "1",
                "h3": "对象存储 OSS"
            }, {
                "or": "false",
                "p": "可弹性扩展、高性能、高可靠的块级随机存储",
                "link": "//www.aliyun.com/product/disk",
                "spm": "disk",
                "tce_rule_count": "1",
                "h3": "块存储"
            }, {
                "or": "false",
                "p": "无限扩展、多共享、标准文件协议的文件存储服务",
                "link": "//www.aliyun.com/product/nas",
                "spm": "nas",
                "tce_rule_count": "1",
                "h3": "文件存储"
            }, {
                "or": "false",
                "p": "高并发、低延时、无限容量的Nosql数据存储服务",
                "link": "//www.aliyun.com/product/ots",
                "spm": "ots",
                "tce_rule_count": "1",
                "h3": "表格存储"
            }, {
                "or": "false",
                "p": "海量数据的长期归档、备份服务",
                "link": "//www.aliyun.com/product/oas/",
                "spm": "oas",
                "tce_rule_count": "1",
                "h3": "归档存储"
            }, {
                "or": "false",
                "p": "跨运营商、跨地域全网覆盖的网络加速服务",
                "link": "//www.aliyun.com/product/cdn",
                "spm": "cdn",
                "tce_rule_count": "1",
                "h3": "CDN"
            }],
            "or": "false",
            "width": "700px",
            "spm": "cunchuCDN",
            "tce_rule_count": "1"
        }, {
            "text": "分析",
            "items": [{
                "or": "false",
                "p": "基于 Hadoop/Spark 的大数据处理分析服务",
                "link": "https://www.aliyun.com/product/emapreduce",
                "spm": "emapreduce2",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "E-MapReduce"
            }, {
                "or": "false",
                "p": "基于Greenplum Database的MPP数据仓库",
                "link": "https://www.aliyun.com/product/gpdb",
                "spm": "Greenplum2",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云数据库 HybridDB"
            }, {
                "or": "false",
                "p": "加速深度学习、渲染和科学计算的 GPU 物理机",
                "link": "https://www.aliyun.com/product/hpc",
                "spm": "HPC2",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "高性能计算 HPC"
            }, {
                "or": "false",
                "p": "TB/PB级数据仓库解决方案",
                "link": "https://www.aliyun.com/product/odps",
                "spm": "MaxCompute2",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "大数据计算服务 MaxCompute"
            }, {
                "or": "false",
                "p": "海量数据实时高并发在线分析",
                "link": "https://www.aliyun.com/product/ads",
                "spm": "ads2",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "分析型数据库"
            }, {
                "or": "false",
                "p": "结构化数据搜索托管服务",
                "link": "https://www.aliyun.com/product/opensearch",
                "spm": "opensearch2",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "开放搜索"
            }],
            "or": "false",
            "width": "700px",
            "spm": "newfenxi",
            "tce_rule_count": "1"
        }, {
            "text": "云通信",
            "items": [{
                "or": "true",
                "p": "验证码和短信通知服务，三网合一快速到达",
                "link": "https://www.aliyun.com/product/sms",
                "spm": "sms",
                "tce_rule_count": "1",
                "h3": "短信服务"
            }, {
                "or": "true",
                "p": "语音通知和语音验证，支持多方通话",
                "link": "https://www.aliyun.com/product/vms",
                "spm": "vms",
                "tce_rule_count": "1",
                "h3": "语音服务"
            }, {
                "or": "true",
                "p": "轻松玩转手机流量，物联卡专供物联终端使用",
                "link": "https://www.aliyun.com/product/cdps",
                "spm": "cdps",
                "tce_rule_count": "1",
                "h3": "流量服务"
            }, {
                "or": "true",
                "p": "号码隔离，保护双方的隐私信息",
                "link": "https://www.aliyun.com/product/pls",
                "spm": "pls",
                "tce_rule_count": "1",
                "h3": "私密专线"
            }, {
                "or": "true",
                "p": "移动应用通知与消息推送服务",
                "link": "https://www.aliyun.com/product/cps",
                "spm": "cps",
                "tce_rule_count": "1",
                "h3": "移动推送"
            }, {
                "or": "true",
                "p": "大规模、高可靠、高并发访问和超强消息堆积能力",
                "link": "https://www.aliyun.com/product/mns",
                "spm": "mns",
                "tce_rule_count": "1",
                "h3": "消息服务"
            }, {
                "or": "true",
                "p": "事务邮件、通知邮件和批量邮件的快速发送",
                "link": "https://www.aliyun.com/product/directmail",
                "spm": "directmail",
                "tce_rule_count": "1",
                "h3": "邮件推送"
            }],
            "or": "false",
            "width": "700px",
            "spm": "yuntongxin",
            "tce_rule_count": "1"
        }, {
            "text": "网络",
            "items": [{
                "or": "false",
                "p": "对多台云服务器进行流量分发的负载均衡服务",
                "link": "//www.aliyun.com/product/slb",
                "spm": "slb",
                "tce_rule_count": "1",
                "h3": "负载均衡"
            }, {
                "or": "false",
                "p": "帮您轻松构建逻辑隔离的专有网络",
                "link": "//www.aliyun.com/product/vpc",
                "spm": "vpc",
                "tce_rule_count": "1",
                "h3": "专有网络 VPC"
            }, {
                "or": "false",
                "p": "高速稳定的 VPC 互联和专线接入服务",
                "link": "//www.aliyun.com/product/expressconnect",
                "spm": "expressconnect",
                "tce_rule_count": "1",
                "h3": "高速通道"
            }, {
                "or": "false",
                "p": "跨运营商、跨地域全网覆盖的网络加速服务",
                "link": "//www.aliyun.com/product/cdn",
                "spm": "cdn",
                "tce_rule_count": "1",
                "h3": "CDN"
            }, {
                "or": "false",
                "p": "支持NAT转发、共享带宽的VPC网关",
                "link": "https://www.aliyun.com/product/nat",
                "spm": "natnet",
                "tce_rule_count": "1",
                "h3": "NAT网关"
            }],
            "or": "false",
            "width": "700px",
            "spm": "wangluo",
            "tce_rule_count": "1"
        }, {
            "text": "管理与监控",
            "items": [{
                "or": "false",
                "p": "指标监控与报警服务",
                "link": "//www.aliyun.com/product/jiankong",
                "spm": "jiankong",
                "tce_rule_count": "1",
                "h3": "云监控"
            }, {
                "or": "false",
                "p": "管理多因素认证、子账号与授权、角色与 STS 令牌",
                "link": "//www.aliyun.com/product/ram",
                "spm": "ram",
                "tce_rule_count": "1",
                "h3": "访问控制"
            }, {
                "or": "false",
                "p": "批量创建、管理、配置云计算资源",
                "link": "//www.aliyun.com/product/ros",
                "spm": "ros",
                "tce_rule_count": "1",
                "h3": "资源编排"
            }, {
                "or": "false",
                "p": "详细记录控制台和 API 操作",
                "link": "//www.aliyun.com/product/actiontrail",
                "spm": "actiontrail",
                "tce_rule_count": "1",
                "h3": "操作审计（公测中）"
            }, {
                "or": "false",
                "p": "安全、易用、低成本的密钥管理服务",
                "link": "//www.aliyun.com/product/kms",
                "spm": "kms",
                "tce_rule_count": "1",
                "h3": "密钥管理服务（公测中）"
            }],
            "or": "false",
            "width": "700px",
            "spm": "guankong",
            "tce_rule_count": "1"
        }, {
            "text": "应用服务",
            "items": [{
                "or": "false",
                "p": "针对日志收集、存储、查询和分析的服务",
                "link": "//www.aliyun.com/product/sls/",
                "spm": "sls",
                "tce_rule_count": "1",
                "h3": "日志服务"
            }, {
                "or": "false",
                "p": "结构化数据搜索托管服务",
                "link": "//www.aliyun.com/product/opensearch",
                "spm": "opensearc",
                "tce_rule_count": "1",
                "h3": "开放搜索"
            }, {
                "or": "false",
                "p": "性能云测试平台，帮您轻松完成系统性能评估",
                "link": "//www.aliyun.com/product/pts",
                "spm": "pts",
                "tce_rule_count": "1",
                "h3": "性能测试"
            }, {
                "or": "false",
                "p": "事务\\批量邮件推送，验证码\\通知短信服务",
                "link": "//www.aliyun.com/product/directmail",
                "spm": "directmail",
                "tce_rule_count": "1",
                "h3": "邮件推送"
            }, {
                "or": "false",
                "p": "高性能、高可用的 API 托管服务，低成本开放 API",
                "link": "//www.aliyun.com/product/apigateway",
                "spm": "apigateway",
                "tce_rule_count": "1",
                "h3": "API 网关"
            }, {
                "or": "false",
                "p": "助您快速搭建稳定可靠的物联网应用",
                "link": "//www.aliyun.com/product/iot",
                "spm": "iot",
                "tce_rule_count": "1",
                "h3": "物联网套件（公测中）"
            }, {
                "or": "false",
                "p": "大规模、高可靠、高并发访问和超强消息堆积能力",
                "link": "//www.aliyun.com/product/mns",
                "spm": "mns",
                "tce_rule_count": "1",
                "h3": "消息服务"
            }],
            "or": "false",
            "width": "700px",
            "spm": "yingyngfuwu",
            "tce_rule_count": "1"
        }, {
            "text": "互联网中间件",
            "items": [{
                "or": "false",
                "p": "以应用为中心的中间件 PaaS 平台",
                "link": "https://www.aliyun.com/product/edas",
                "spm": "edas",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "企业级分布式应用服务 EDAS"
            }, {
                "or": "false",
                "p": "Apache RocketMQ商用版企业级异步通信中间件",
                "link": "https://www.aliyun.com/product/ons",
                "spm": "ons",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "消息队列 MQ"
            }, {
                "or": "false",
                "p": "水平拆分/读写分离的在线分布式数据库服务",
                "link": "https://www.aliyun.com/product/drds",
                "spm": "drds",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "分布式关系型数据库服务 DRDS"
            }, {
                "or": "false",
                "p": "企业级互联网能力开放平台",
                "link": "https://www.aliyun.com/product/csb",
                "spm": "csbcsb",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云服务总线 CSB（公测中）"
            }, {
                "or": "false",
                "p": "端到端一体化实时监控解决方案产品",
                "link": "https://www.aliyun.com/product/arms",
                "spm": "armsarms",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "业务实时监控服务 ARMS（公测中）"
            }],
            "or": "false",
            "width": "700px",
            "spm": "zhognjianjian",
            "tce_rule_count": "1"
        }, {
            "text": "移动服务",
            "items": [{
                "or": "false",
                "p": "移动应用通知与消息推送服务",
                "link": "https://www.aliyun.com/product/cps",
                "spm": "cps",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "移动推送"
            }, {
                "or": "true",
                "p": "验证码和短信通知服务，三网合一快速到达",
                "link": "https://www.aliyun.com/product/sms",
                "spm": "smssms",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "短信服务"
            }, {
                "or": "false",
                "p": "移动应用域名防劫持和精确调度服务",
                "link": "https://www.aliyun.com/product/httpdns",
                "spm": "httpdns",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "HTTPDNS"
            }, {
                "or": "false",
                "p": "为移动应用提供全生命周期安全服务",
                "link": "https://www.aliyun.com/product/mobsec",
                "spm": "mobilesave",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "移动安全"
            }, {
                "or": "false",
                "p": "移动应用数据采集、分析、展示和数据输出服务",
                "link": "https://www.aliyun.com/product/man",
                "spm": "man",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "移动数据分析（公测中）"
            }, {
                "or": "false",
                "p": "移动应用访问加速",
                "link": "https://www.aliyun.com/product/mac",
                "spm": "mac",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "移动加速（公测中）"
            }],
            "or": "false",
            "width": "700px",
            "spm": "yidongfuwu",
            "tce_rule_count": "1"
        }, {
            "text": "视频服务",
            "items": [{
                "or": "false",
                "p": "安全、弹性、高可定制的点播服务",
                "link": "https://www.aliyun.com/product/vod",
                "spm": "vod",
                "tce_rule_count": "1",
                "h3": "视频点播"
            }, {
                "or": "false",
                "p": "为多媒体数据提供的转码计算服务",
                "link": "https://www.aliyun.com/product/mts",
                "spm": "mts",
                "tce_rule_count": "1",
                "h3": "媒体转码"
            }, {
                "or": "false",
                "p": "低延迟、高并发的音视频直播服务",
                "link": "https://www.aliyun.com/product/live",
                "spm": "live",
                "tce_rule_count": "1",
                "h3": "视频直播"
            }],
            "or": "false",
            "width": "700px",
            "spm": "shipinfuwu",
            "tce_rule_count": "1"
        }], "key": "product_elastic"
    }, {
        "items": [{
            "text": "行业解决方案",
            "items": [{
                "or": "true",
                "p": "依据不同发展阶段，提供一站式建站方案",
                "link": "https://www.aliyun.com/solution/web",
                "spm": "websolution",
                "tce_rule_count": "1",
                "tips": "new",
                "h3": "网站解决方案"
            }, {
                "or": "true",
                "p": "轻松应对移动app爆发式增长",
                "link": "https://www.aliyun.com/solution/app",
                "spm": "appsolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "移动APP解决方案"
            }],
            "or": "true",
            "width": "700px",
            "tce_rule_count": "1"
        }, {
            "text": "通用解决方案",
            "items": [{
                "or": "false",
                "p": "依据不同发展阶段，提供一站式建站方案",
                "link": "https://www.aliyun.com/solution/web",
                "spm": "wangzhsolution",
                "tce_rule_count": "1",
                "tips": "new",
                "h3": "网站解决方案"
            }, {
                "or": "false",
                "p": "轻松应对移动app爆发式增长",
                "link": "https://www.aliyun.com/solution/app",
                "spm": "yidongAPPsolution",
                "tce_rule_count": "1",
                "tips": "new",
                "h3": "移动APP解决方案"
            }, {
                "or": "false",
                "p": "帮助客户向混合云架构平滑演进",
                "link": "https://www.aliyun.com/solution/dedicatedcloud",
                "spm": "zhuanyouyunsolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "专有云解决方案"
            }, {
                "or": "false",
                "p": "多元解决方案，带给企业云端新技术",
                "link": "https://www.aliyun.com/solution/hcloud",
                "spm": "hcloudsolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "混合云解决方案"
            }, {
                "or": "false",
                "p": "确保数据不丢失，保证恢复",
                "link": "https://www.aliyun.com/solution/recovery",
                "spm": "recovery",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "容灾解决方案"
            }, {
                "or": "false",
                "p": "多层防护+云端大数据，提供整套安全产品和服务",
                "link": "https://www.aliyun.com/solution/security",
                "spm": "security",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "安全解决方案"
            }, {
                "or": "false",
                "p": "解决海量数据存档/备份、加工，加速分发等问题",
                "link": "https://www.aliyun.com/solution/storage",
                "spm": "storage",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云存储解决方案"
            }, {
                "or": "false",
                "p": "经历阿里巴巴电商考验，助企业快速构建分布式应用",
                "link": "https://www.aliyun.com/solution/middleware",
                "spm": "middleware",
                "tce_rule_count": "1",
                "tips": "new",
                "h3": "企业互联网架构方案"
            }, {
                "or": "false",
                "p": "帮助传统硬件负载均衡用户快速、平滑迁移到云平台",
                "link": "https://www.aliyun.com/solution/adn",
                "spm": "adn",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "应用交付网络解决方案"
            }, {
                "or": "false",
                "p": "高效高质输出运输方案，显著降低运输成本",
                "link": "https://data.aliyun.com/solution/dispatch",
                "spm": "dispatch",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "智能配送调度解决方案"
            }, {
                "or": "false",
                "p": "便捷3D模型导入、ET语音交互,助力VR开发者",
                "link": "https://data.aliyun.com/solution/vr",
                "spm": "vr",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "VR应用开发解决方案"
            }, {
                "or": "false",
                "p": "建立等保合规生态，提供一站式等保合规方案",
                "link": "https://www.aliyun.com/solution/classifiedprotection.html",
                "spm": "classifiedprotection",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "等级保护安全合规方案"
            }],
            "or": "true",
            "width": "1030px",
            "tce_rule_count": "1"
        }, {
            "text": "大数据解决方案",
            "items": [{
                "or": "false",
                "p": "根据用户行为，推荐用户感兴趣的信息和商品",
                "link": "https://data.aliyun.com/solution/re",
                "spm": "re",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "个性化推荐"
            }, {
                "or": "false",
                "p": "提供从数据采集、存储加工、管理等数仓解决方案",
                "link": "https://data.aliyun.com/solution/base",
                "spm": "base",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "大数据仓库"
            }, {
                "or": "false",
                "p": "提供可跨异构数据存储系统、安全可靠低成本",
                "link": "https://data.aliyun.com/solution/cdp",
                "spm": "cdp",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云上数据集成方案"
            }, {
                "or": "false",
                "p": "提供从5min到未来1h精准度92%的路况拥堵预测",
                "link": "https://data.aliyun.com/solution/rp",
                "spm": "rp",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "路况预测"
            }, {
                "or": "false",
                "p": "判断台风未来的走向及汛情，帮助做出决策",
                "link": "https://data.aliyun.com/solution/tiqas",
                "spm": "tiqas",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "台风路径分析"
            }, {
                "or": "false",
                "p": "帮助您从无到有快速搭建自有营销推广系统",
                "link": "https://data.aliyun.com/solution/dm",
                "spm": "dm",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "数字营销解决方案"
            }, {
                "or": "false",
                "p": "为工业客户提供基于人工智能的解决方案",
                "link": "https://data.aliyun.com/solution/industry",
                "spm": "industry",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "工业大数据服务解决方案"
            }, {
                "or": "false",
                "p": "多位交叉分析及智能算法",
                "link": "https://data.aliyun.com/solution/cds",
                "spm": "cds",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "企业数据服务解决方案"
            }],
            "or": "true",
            "width": "700px",
            "tce_rule_count": "1"
        }], "key": "solution_tp1"
    }],
    "tpl2": [{
        "items": [{
            "title": "数据应用",
            "items": [{
                "text": "推荐引擎",
                "or": "false",
                "p": "实时在线推荐，首月仅需1元！",
                "link": "https://data.aliyun.com/product/re",
                "spm": "bdtuijianyinqin",
                "tce_rule_count": "1"
            }, {
                "text": "公众趋势分析",
                "or": "false",
                "p": "公众情感分析、舆情感知",
                "link": "https://data.aliyun.com/product/prophet",
                "spm": "bdgongzhqsfx",
                "tce_rule_count": "1"
            }, {
                "text": "企业图谱",
                "or": "false",
                "p": "深度挖掘企业和个人关系链",
                "link": "https://data.aliyun.com/product/eprofile",
                "spm": "qiyetupu",
                "tce_rule_count": "1"
            }, {
                "text": "数据集成（公测中）",
                "or": "false",
                "p": "稳定高效、弹性伸缩的数据同步平台",
                "link": "https://www.aliyun.com/product/cdp/",
                "spm": "bdshujujicheng",
                "tce_rule_count": "1"
            }, {
                "text": "数据市场相关API及应用",
                "or": "true",
                "p": "打造全行业数据共享服务体验，让数据连接你我他",
                "link": "https://market.aliyun.com/store/1334330-0.html",
                "spm": "bddatamarket",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "spm": "dataapp",
            "tce_rule_count": "1"
        }, {
            "title": "数据分析展现",
            "items": [{
                "text": "DataV数据可视化",
                "or": "false",
                "p": "创造属于您的双11指挥大屏！￥0.99 元使用3个月",
                "link": "https://data.aliyun.com/visual/datav",
                "spm": "bddatavisual",
                "tce_rule_count": "1"
            }, {
                "text": "Quick BI（公测中）",
                "or": "false",
                "p": "极致简单、零SQL报表多维分析",
                "link": "https://data.aliyun.com/product/bi",
                "spm": "bdqickbi",
                "tce_rule_count": "1"
            }, {
                "text": "画像分析（公测中）",
                "or": "false",
                "p": "基于标签模型构建大数据画像类的交互式分析应用",
                "link": "https://data.aliyun.com/product/porana",
                "spm": "bdimageanysis",
                "tce_rule_count": "1"
            }, {
                "text": "I+关系网络分析",
                "or": "false",
                "p": "基于关系网络的大数据可视化分析平台",
                "link": "https://data.aliyun.com/product/graphanalytics",
                "spm": "graphanalytics",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "spm": "dataadis",
            "tce_rule_count": "1"
        }, {
            "title": "人工智能",
            "items": [{
                "text": "机器学习",
                "or": "false",
                "p": "集合了阿里集团大量优质算法",
                "link": "https://data.aliyun.com/product/learn",
                "spm": "bdjiqilearn",
                "tce_rule_count": "1"
            }, {
                "text": "语音识别与合成",
                "or": "false",
                "p": "提供语音转文本、文本转语音的服务",
                "link": "https://data.aliyun.com/product/nls",
                "spm": "yuyinshibie",
                "tce_rule_count": "1"
            }, {
                "text": "人机对话",
                "or": "false",
                "p": "提供快速搭建人机对话机器人的智能平台",
                "link": "https://data.aliyun.com/product/nls",
                "spm": "renjiduihua",
                "tce_rule_count": "1"
            }, {
                "text": "印刷文字识别（公测中）",
                "or": "false",
                "p": "证件类及自然场景图片的中英文文字检测和识别",
                "link": "https://data.aliyun.com/product/ocr",
                "spm": "bdprintcode",
                "tce_rule_count": "1"
            }, {
                "text": "人脸识别（公测中）",
                "or": "false",
                "p": "图像和视频帧中人脸分析的在线服务",
                "link": "https://data.aliyun.com/product/face",
                "spm": "bdfacescan",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "spm": "dataet",
            "tce_rule_count": "1"
        }, {
            "title": "大数据基础服务",
            "items": [{
                "text": "大数据开发套件",
                "or": "false",
                "p": "可视化开发界面、离线任务调度运维",
                "link": "https://data.aliyun.com/product/ide",
                "spm": "bdbddevpack",
                "tce_rule_count": "1"
            }, {
                "text": "分析型数据库",
                "or": "false",
                "p": "海量数据实时高并发在线分析",
                "link": "https://www.aliyun.com/product/ads",
                "spm": "bdanysisdtbs",
                "tce_rule_count": "1"
            }, {
                "text": "MaxCompute",
                "or": "false",
                "p": "TB/PB级数据仓库解决方案",
                "link": "https://www.aliyun.com/product/odps",
                "spm": "maxcomp",
                "tce_rule_count": "1"
            }, {
                "text": "流计算（公测中）",
                "or": "false",
                "p": "流式数据实时化分析工具",
                "link": "https://data.aliyun.com/product/sc",
                "spm": "liucomp",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "spm": "databasesv",
            "tce_rule_count": "1"
        }], "key": "product_database"
    }, {
        "items": [{
            "title": "基础软件市场",
            "items": [{
                "text": "预装Windows",
                "or": "true",
                "link": "https://market.aliyun.com/products/53366009/?keyword=windows&amp;filter=priceTag%3Aall%2CadaptSystem%3Aall%2CdeliveryMethod%3A%E9%95%9C%E5%83%8F%2Clanguage%3Aall&amp;order=score-desc&amp;category=53366009",
                "spm": "mkyuzhwin",
                "tce_rule_count": "1"
            }, {
                "text": "预装Linux",
                "or": "true",
                "link": "https://market.aliyun.com/products/53366009/?keyword=Linux&amp;filter=priceTag%3Aall%2CadaptSystem%3Aall%2CdeliveryMethod%3A镜像%2Clanguage%3Aall&amp;order=score-desc#ymk=%7B%22categoryId%22:53366009,%22deliveryMethod%22:%22%E9%95%9C%E5%83%8F%22,%22keywords%22:%22Linux%22,%22pageIndex%22:1,%22pageSize%22:10,%22saleMode%22:0,%22sort%22:%22score-desc%22%7D",
                "spm": "mkyuzhlinux",
                "tce_rule_count": "1"
            }, {
                "text": "预装PHP环境",
                "or": "true",
                "link": "https://market.aliyun.com/products/53398003/",
                "spm": "mkyuzhphp",
                "tce_rule_count": "1"
            }, {
                "text": "预装JAVA环境",
                "or": "true",
                "link": "https://market.aliyun.com/products/53400005/",
                "spm": "mkyuzhjava",
                "tce_rule_count": "1"
            }, {
                "text": "预装ASP/.NET",
                "or": "true",
                "link": "https://market.aliyun.com/products/53448001/?tag=&amp;filter=priceTag%3Aall%2CdeliveryMethod%3Aall%2CadaptSystem%3Aall%2Clanguage%3Aasp.net",
                "spm": "mkyuzhaspnet",
                "tce_rule_count": "1"
            }, {
                "text": "预装全能环境",
                "or": "true",
                "link": "https://market.aliyun.com/products/56092004",
                "spm": "mkyuzhal",
                "tce_rule_count": "1"
            }],
            "or": "true",
            "link": "https://market.aliyun.com/software",
            "spm": "mkbaseapp",
            "tce_rule_count": "1"
        }, {
            "title": "网站建设",
            "items": [{
                "text": "企业官网定制",
                "or": "true",
                "link": "https://market.aliyun.com/products/52738005",
                "spm": "mkqiyewangzh",
                "tce_rule_count": "1"
            }, {
                "text": "电商网站定制",
                "or": "true",
                "link": "https://market.aliyun.com/products/52750001/?spm=5176.730005-52750001.313509.149.AH98VI#ymk=%7B%22categoryId%22:52750001,%22pageIndex%22:1,%22pageSize%22:10,%22saleMode%22:0%7D",
                "spm": "mkdswangzh",
                "tce_rule_count": "1"
            }, {
                "text": "精美网站模板",
                "or": "true",
                "link": "https://market.aliyun.com/tpldns",
                "spm": "mkjmwangzh",
                "tce_rule_count": "1"
            }, {
                "text": "手机网站定制",
                "or": "true",
                "link": "https://market.aliyun.com/products/52752001",
                "spm": "mkshoujiwangzh",
                "tce_rule_count": "1"
            }, {
                "text": "APP定制开发",
                "or": "true",
                "link": "https://market.aliyun.com/products/55514022",
                "spm": "mkappdev",
                "tce_rule_count": "1"
            }, {
                "text": "量身定制服务",
                "or": "true",
                "link": "https://market.aliyun.com/task.html",
                "spm": "mkpersonaldev",
                "tce_rule_count": "1"
            }],
            "or": "true",
            "link": "https://market.aliyun.com/jianzhan",
            "spm": "mksitejz",
            "tce_rule_count": "1"
        }, {
            "title": "企业应用",
            "items": [{
                "text": "公司/商标注册等服务",
                "or": "true",
                "link": "https://market.aliyun.com/eservice",
                "spm": "shangbiaozhucefuwu",
                "tce_rule_count": "1"
            }, {
                "text": "阿里云办公",
                "or": "true",
                "link": "https://promotion.aliyun.com/ntms/market/c-office.html?spm=5176.8142029.414693.20.GR0ks7",
                "spm": "mkaliyunbg",
                "tce_rule_count": "1"
            }, {
                "text": "销售管理",
                "or": "true",
                "link": "https://market.aliyun.com/products/56842010/?tag=&amp;keyword=&amp;saleMode=",
                "spm": "mkaliyunxsgl",
                "tce_rule_count": "1"
            }, {
                "text": "财务管理",
                "or": "true",
                "link": "https://market.aliyun.com/products/56764034",
                "spm": "mkaliyuncwgl",
                "tce_rule_count": "1"
            }, {
                "text": "协同办公",
                "or": "true",
                "link": "https://market.aliyun.com/products/56778013",
                "spm": "mkaliyunxt",
                "tce_rule_count": "1"
            }, {
                "text": "人事管理",
                "or": "true",
                "link": "https://market.aliyun.com/products/56780006",
                "spm": "mkaliyunrsgl",
                "tce_rule_count": "1"
            }],
            "or": "true",
            "link": "https://market.aliyun.com/enterprise",
            "spm": "mkentapp",
            "tce_rule_count": "1"
        }, {
            "title": "服务与培训",
            "items": [{
                "text": "环境配置",
                "or": "true",
                "link": "https://market.aliyun.com/products/?tag=环境配置",
                "spm": "mkenviset",
                "tce_rule_count": "1"
            }, {
                "text": "培训与认证",
                "or": "true",
                "link": "https://market.aliyun.com/products/?tag=阿里云产品培训",
                "spm": "mkpeixunnrz",
                "tce_rule_count": "1"
            }, {
                "text": "服务器代维",
                "or": "true",
                "link": "https://market.aliyun.com/products/52732002",
                "spm": "mkfuwqidai",
                "tce_rule_count": "1"
            }, {
                "text": "数据迁移",
                "or": "true",
                "link": "https://market.aliyun.com/products/52738004",
                "spm": "mkdataqianyi",
                "tce_rule_count": "1"
            }, {
                "text": "故障排查",
                "or": "true",
                "link": "https://market.aliyun.com/products/52740002",
                "spm": "mkbugdetc",
                "tce_rule_count": "1"
            }, {
                "text": "行业解决方案",
                "or": "true",
                "link": "https://market.aliyun.com/solutions",
                "spm": "mkzixunjiagou",
                "tce_rule_count": "1"
            }],
            "or": "true",
            "link": "https://market.aliyun.com/service",
            "spm": "mksvandedu",
            "tce_rule_count": "1"
        }, {
            "title": "安全市场",
            "items": [{
                "text": "网络安全",
                "or": "true",
                "link": "https://market.aliyun.com/products/56820014",
                "spm": "mknetsv",
                "tce_rule_count": "1"
            }, {
                "text": "主机安全",
                "or": "true",
                "link": "https://market.aliyun.com/products/56832023",
                "spm": "mkzhujsv",
                "tce_rule_count": "1"
            }, {
                "text": "应用安全",
                "or": "true",
                "link": "https://market.aliyun.com/products/56846020",
                "spm": "mkappsv",
                "tce_rule_count": "1"
            }, {
                "text": "数据安全",
                "or": "true",
                "link": "https://market.aliyun.com/products/56824015",
                "spm": "mkdatasv",
                "tce_rule_count": "1"
            }, {
                "text": "安全管理",
                "or": "true",
                "link": "https://market.aliyun.com/products/56830014",
                "spm": "mksvmanage",
                "tce_rule_count": "1"
            }, {
                "text": "安全服务",
                "or": "true",
                "link": "https://market.aliyun.com/products/57004003",
                "spm": "mksvservice",
                "tce_rule_count": "1"
            }],
            "or": "true",
            "link": "https://market.aliyun.com/security",
            "spm": "mksecuritymk",
            "tce_rule_count": "1"
        }, {
            "title": "数据及API",
            "items": [{
                "text": "金融理财",
                "or": "true",
                "link": "https://market.aliyun.com/products/56928004?spm=5176.78296.419699.1.LgXe83#ymk=%7B%22categoryId%22:57000002,%22pageIndex%22:1,%22pageSize%22:10,%22saleMode%22:0%7D",
                "spm": "mkdianzishangwu",
                "tce_rule_count": "1"
            }, {
                "text": "电子商务",
                "or": "true",
                "link": "https://market.aliyun.com/products/56928004?spm=5176.78296.419699.4.LgXe83#ymk=%7B%22categoryId%22:56928004,%22pageIndex%22:1,%22pageSize%22:10,%22saleMode%22:0%7D",
                "spm": "mkdzsw",
                "tce_rule_count": "1"
            }, {
                "text": "人工智能",
                "or": "true",
                "link": "https://market.aliyun.com/products/56956004/?spm=5176.78296.419699.7.LgXe83#ymk=%7B%22categoryId%22:57124001,%22pageIndex%22:1,%22pageSize%22:10,%22saleMode%22:0%7D",
                "spm": "mkrgzn",
                "tce_rule_count": "1"
            }, {
                "text": "生活服务",
                "or": "true",
                "link": "https://market.aliyun.com/products/56956004/?spm=5176.78296.419699.10.LgXe83#ymk=%7B%22categoryId%22:57126001,%22pageIndex%22:1,%22pageSize%22:10,%22saleMode%22:0%7D",
                "spm": "mkshfw",
                "tce_rule_count": "1"
            }, {
                "text": "交通地理",
                "or": "true",
                "link": "https://market.aliyun.com/products/56928004?spm=5176.78296.419699.13.LgXe83#ymk=%7B%22categoryId%22:57002002,%22pageIndex%22:1,%22pageSize%22:10,%22saleMode%22:0%7D",
                "spm": "mkjtdl",
                "tce_rule_count": "1"
            }, {
                "text": "企业管理",
                "or": "true",
                "link": "https://market.aliyun.com/products/56928005?spm=5176.78296.419699.19.LgXe83#ymk=%7B%22categoryId%22:56928005,%22pageIndex%22:1,%22pageSize%22:10,%22saleMode%22:0%7D",
                "spm": "mkqygl",
                "tce_rule_count": "1"
            }],
            "or": "true",
            "link": "https://market.aliyun.com/data",
            "spm": "mkdatamk",
            "tce_rule_count": "1"
        }], "key": "market"
    }, {
        "items": [{
            "title": "博客",
            "items": [{
                "text": "个人博客",
                "or": "true",
                "link": "https://yq.aliyun.com/articles",
                "spm": "yqpersonalbg",
                "tce_rule_count": "1"
            }, {
                "text": "公众号",
                "or": "true",
                "link": "https://yq.aliyun.com/teams",
                "spm": "yqpublicid",
                "tce_rule_count": "1"
            }],
            "or": "true",
            "link": "https://yq.aliyun.com/articles",
            "spm": "combolg",
            "tce_rule_count": "1"
        }, {
            "title": "论坛",
            "items": [{
                "text": "产品讨论",
                "or": "true",
                "link": "https://bbs.aliyun.com/fourms.php?m=bbs&amp;cateid=33",
                "spm": "yqproductdiz",
                "tce_rule_count": "1"
            }, {
                "text": "开发者中心",
                "or": "true",
                "link": "https://bbs.aliyun.com/fourms.php?&amp;m=bbs&amp;cateid=228",
                "spm": "kfzzhongxin",
                "tce_rule_count": "1"
            }, {
                "text": "新手帮帮团",
                "or": "true",
                "link": "https://bbs.aliyun.com/thread/235.html",
                "spm": "xinshoubbt",
                "tce_rule_count": "1"
            }, {
                "text": "域名交易专区",
                "or": "true",
                "link": "https://bbs.aliyun.com/thread/217.html",
                "spm": "yumingjy",
                "tce_rule_count": "1"
            }],
            "or": "true",
            "link": "https://bbs.aliyun.com",
            "spm": "combbs",
            "tce_rule_count": "1"
        }, {
            "title": "问答",
            "items": [{
                "text": "热门问答",
                "or": "true",
                "link": "https://yq.aliyun.com/ask",
                "spm": "yqtopques",
                "tce_rule_count": "1"
            }, {
                "text": "通用技术",
                "or": "true",
                "link": "https://yq.aliyun.com/ask/type_tech",
                "spm": "yqcomtech",
                "tce_rule_count": "1"
            }, {
                "text": "产品求助",
                "or": "true",
                "link": "https://yq.aliyun.com/ask/type_aliyun",
                "spm": "yqprohelp",
                "tce_rule_count": "1"
            }],
            "or": "true",
            "link": "https://yq.aliyun.com/ask",
            "spm": "comask",
            "tce_rule_count": "1"
        }, {
            "title": "云课堂",
            "items": [{
                "text": "云栖直播",
                "or": "true",
                "link": "https://yq.aliyun.com/edu/lessonTagSearch/cid_695-tagid_14065",
                "spm": "yqzhibo",
                "tce_rule_count": "1"
            }, {
                "text": "产品学习",
                "or": "true",
                "link": "https://yq.aliyun.com/edu/lessonTagSearch/cid_14053",
                "spm": "chanpinxx",
                "tce_rule_count": "1"
            }, {
                "text": "开发技术",
                "or": "true",
                "link": "http://yq.aliyun.com/edu/lessonTagSearch/cid_14061",
                "spm": "kfajishu",
                "tce_rule_count": "1"
            }],
            "or": "true",
            "link": "https://yq.aliyun.com/edu/lesson",
            "spm": "comcollege",
            "tce_rule_count": "1"
        }], "key": "community"
    }],
    "tpl3": [{
        "items": [{
            "title": "防御",
            "items": [{
                "text": "服务器安全（安骑士）",
                "or": "false",
                "p": "安全运维管理平台，入侵检测、漏洞批量修复",
                "link": "https://www.aliyun.com/product/aegis",
                "spm": "aqanqishi",
                "tce_rule_count": "1"
            }, {
                "text": "Web应用防火墙（网络安全）",
                "or": "false",
                "p": "防SQL注入、防CC、防网站入侵、防接口被刷",
                "link": "https://www.aliyun.com/product/waf",
                "spm": "aqwebdefend",
                "tce_rule_count": "1"
            }, {
                "text": "加密服务（数据安全）",
                "or": "false",
                "p": "云上用户的数据加密解决方案",
                "link": "https://www.aliyun.com/product/hsm",
                "spm": "aqendataaq",
                "tce_rule_count": "1"
            }, {
                "text": "数据风控（业务安全）",
                "or": "false",
                "p": "防垃圾注册、刷库撞库、活动作弊、论坛灌水",
                "link": "https://www.aliyun.com/product/antifraud",
                "spm": "shujufengk",
                "tce_rule_count": "1"
            }, {
                "text": "移动安全",
                "or": "false",
                "p": "针对移动APP提供漏洞扫描，应用加固等安全服务",
                "link": "https://www.aliyun.com/product/mobsec",
                "spm": "aqmobilesv",
                "tce_rule_count": "1"
            }, {
                "text": "数据安全险（安全服务）",
                "or": "false",
                "p": "因黑客攻击导致数据泄露，最高赔偿100万",
                "link": "https://www.aliyun.com/product/dsi",
                "spm": "aqdatamanager",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "tce_rule_count": "1"
        }, {
            "title": "&nbsp;",
            "items": [{
                "text": "DDoS高防IP（网络安全）",
                "or": "false",
                "p": "20-300G防护，按天计算，轻松应对大流量攻击",
                "link": "https://www.aliyun.com/product/ddos",
                "spm": "aqddossv",
                "tce_rule_count": "1"
            }, {
                "text": "安全管家（安全服务）",
                "or": "false",
                "p": "紧急安全事件入侵分析排查和修复",
                "link": "https://www.aliyun.com/product/sos",
                "spm": "aqsossv",
                "tce_rule_count": "1"
            }, {
                "text": "绿网（内容安全）",
                "or": "false",
                "p": "专注违规信息安全监测及管控",
                "link": "https://www.aliyun.com/product/lvwang",
                "spm": "aqgreennet",
                "tce_rule_count": "1"
            }, {
                "text": "CA证书服务（数据安全）",
                "or": "false",
                "p": "提供一站式的数字证书申请和应用服务",
                "link": "https://www.aliyun.com/product/cas",
                "spm": "aqzhengshusv",
                "tce_rule_count": "1"
            }, {
                "text": "合作伙伴产品中心",
                "or": "false",
                "p": "阿里云依赖的合作伙伴提供的专业安全产品与服务",
                "link": "https://www.aliyun.com/product/sppc",
                "spm": "aqcorporatectr",
                "tce_rule_count": "1"
            }, {
                "text": "云盾混合云",
                "or": "false",
                "p": "全方位互联网安全攻防体系",
                "link": "https://www.aliyun.com/product/shc",
                "spm": "shcsc",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "tce_rule_count": "1"
        }, {
            "title": "检测",
            "items": [{
                "text": "态势感知（大数据安全）",
                "or": "false",
                "p": "安全大数据分析，监控漏洞攻击，预警入侵风险",
                "link": "https://www.aliyun.com/product/sas",
                "spm": "aqtaishiganzhi",
                "tce_rule_count": "1"
            }, {
                "text": "先知（安全情报）",
                "or": "false",
                "p": "私密安全众测，安全漏洞按效果付费",
                "link": "https://www.aliyun.com/product/xianzhi",
                "spm": "aqaqqingbao",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "tce_rule_count": "1"
        }], "key": "product_yundun"
    }, {
        "items": [{
            "title": "重要频道",
            "items": [{
                "text": "万网",
                "or": "false",
                "link": "https://wanwang.aliyun.com/",
                "spm": "morewanwang",
                "tce_rule_count": "1"
            }, {
                "text": "云盾",
                "or": "false",
                "link": "https://yundun.aliyun.com",
                "spm": "moreyundun",
                "tce_rule_count": "1"
            }, {
                "text": "企业级互联网架构 Aliware",
                "or": "false",
                "link": "https://www.aliyun.com/aliware",
                "spm": "morezhongjj",
                "tce_rule_count": "1"
            }, {
                "text": "定价",
                "or": "false",
                "link": "https://www.aliyun.com/price",
                "spm": "moreprice",
                "tce_rule_count": "1"
            }, {
                "text": "客户案例",
                "or": "false",
                "link": "https://www.aliyun.com/customer/",
                "spm": "morecustomer",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "tce_rule_count": "1"
        }, {
            "title": "快速入口",
            "items": [{
                "text": "备案",
                "or": "false",
                "link": "https://beian.aliyun.com/",
                "spm": "fastbeian",
                "tce_rule_count": "1"
            }, {
                "text": "阿里邮箱",
                "or": "true",
                "link": "https://mail.aliyun.com/",
                "spm": "fastalimail",
                "tce_rule_count": "1"
            }, {
                "text": "手机APP",
                "or": "true",
                "link": "https://promotion.aliyun.com/ntms/mobile.html",
                "spm": "fastmobileapp",
                "tce_rule_count": "1"
            }, {
                "text": "新产品发布台",
                "or": "false",
                "link": "https://www.aliyun.com/product/newedtion",
                "spm": "newnwenw",
                "tce_rule_count": "1"
            }, {
                "text": "阿里云品牌形象全新升级",
                "or": "true",
                "link": "https://brand.aliyun.com/",
                "spm": "brandup",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "tce_rule_count": "1"
        }], "key": "more_passageway"
    }, {
        "items": [{
            "title": "云合作",
            "items": [{
                "text": "加入合作伙伴",
                "or": "false",
                "link": "https://partner.aliyun.com",
                "spm": "entercorp",
                "tce_rule_count": "1"
            }, {
                "text": "解决方案合作",
                "or": "false",
                "link": "https://partner.aliyun.com/list/solution.html",
                "spm": "cpsolution",
                "tce_rule_count": "1"
            }, {
                "text": "云服务合作",
                "or": "false",
                "link": "https://partner.aliyun.com/list/cloud.html",
                "spm": "cpyunsv",
                "tce_rule_count": "1"
            }, {
                "text": "技术平台合作",
                "or": "false",
                "link": "https://partner.aliyun.com/list/technical.html",
                "spm": "cptechsite",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "tce_rule_count": "1"
        }, {
            "title": "&nbsp;",
            "items": [{
                "text": "数梦工场合作",
                "or": "false",
                "link": "https://partner.aliyun.com/shumeng",
                "spm": "cpdatapd",
                "tce_rule_count": "1"
            }, {
                "text": "CPS推广合作",
                "or": "false",
                "link": "https://promotion.aliyun.com/ntms/act/aliyun/cps.html",
                "spm": "cpcpstui2016",
                "tce_rule_count": "1"
            }, {
                "text": "蚂蚁金服开放合作",
                "or": "false",
                "link": "https://open.alipay.com/platform/home.htm?from=aliyunshengtai20160825",
                "spm": "antopen",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "tce_rule_count": "1"
        }, {
            "title": "云扶持",
            "items": [{
                "text": "公益扶持",
                "or": "false",
                "link": "https://promotion.aliyun.com/ntms/csr.html",
                "spm": "fuchigongyi",
                "tce_rule_count": "1"
            }, {
                "text": "学生扶持",
                "or": "false",
                "link": "https://promotion.aliyun.com/ntms/campus.html",
                "spm": "fuchixuesheng",
                "tce_rule_count": "1"
            }, {
                "text": "企业小额贷款",
                "or": "true",
                "link": "http://dai.aliloan.com/aliyun.html",
                "spm": "fuchiqiyedaik",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "tce_rule_count": "1"
        }], "key": "more_ecology"
    }, {
        "items": [{
            "title": "阿里巴巴创新中心",
            "items": [{
                "text": "创业扶持-风池计划",
                "or": "false",
                "link": "https://chuangke.aliyun.com/markets/aliyun/surpportive",
                "spm": "ckchaungyefc",
                "tce_rule_count": "1"
            }, {
                "text": "融资申请",
                "or": "false",
                "link": "https://chuangke.aliyun.com/finance",
                "spm": "ckrongzisq",
                "tce_rule_count": "1"
            }, {
                "text": "孵化园/园区入驻",
                "or": "false",
                "link": "https://chuangke.aliyun.com/incubator",
                "spm": "ckfuhuaruzhu",
                "tce_rule_count": "1"
            }, {
                "text": "创业大学",
                "or": "false",
                "link": "https://chuangke.aliyun.com/college",
                "spm": "ckchuangyedx",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "link": "https://chuangke.aliyun.com",
            "spm": "educhkplus",
            "tce_rule_count": "1"
        }, {
            "title": "云栖小镇",
            "items": [{
                "text": "淘富成真",
                "or": "false",
                "link": "https://chuangke.aliyun.com/markets/aliyun/taofuchengzhen",
                "spm": "cktfcz",
                "tce_rule_count": "1"
            }, {
                "text": "淘富成真见面会",
                "or": "false",
                "link": "https://chuangke.aliyun.com/markets/aliyun/taofumeeting",
                "spm": "cktfczjmh",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "spm": "eduyunqitown",
            "tce_rule_count": "1"
        }, {
            "title": "培训认证",
            "items": [{
                "text": "视频课程",
                "or": "false",
                "link": "https://www.aliyun.com/support/video",
                "spm": "pxshipin",
                "tce_rule_count": "1"
            }, {
                "text": "培训课程",
                "or": "false",
                "link": "https://www.aliyun.com/support/courses",
                "spm": "pxeixuncs",
                "tce_rule_count": "1"
            }, {
                "text": "考试认证",
                "or": "false",
                "link": "https://www.aliyun.com/support/certification",
                "spm": "pxpeixunks",
                "tce_rule_count": "1"
            }],
            "or": "false",
            "link": "https://www.aliyun.com/support/training",
            "spm": "edupeixunrz",
            "tce_rule_count": "1"
        }], "key": "more_education"
    }],
    "tpl4": [{
        "items": [{
            "or1": "false",
            "or2": "false",
            "title1": "域名注册",
            "spm2": "wwyuxuni",
            "link2": "https://wanwang.aliyun.com/hosting",
            "spm1": "wwyumingzhuce",
            "title2": "云虚拟主机",
            "items2": [{
                "or": "false",
                "link": "https://wanwang.aliyun.com/hosting",
                "half": "false",
                "spm": "wwxunidux",
                "tce_rule_count": "1",
                "h3": "独享云虚拟主机"
            }, {
                "or": "false",
                "link": "https://wanwang.aliyun.com/hosting",
                "half": "false",
                "spm": "wwxunigongxx",
                "tce_rule_count": "1",
                "h3": "共享云虚拟主机"
            }, {
                "or": "false",
                "link": "https://wanwang.aliyun.com/hosting/elastic/",
                "half": "false",
                "spm": "wwtanxingtg",
                "tce_rule_count": "1",
                "h3": "弹性Web托管"
            }],
            "link1": "https://wanwang.aliyun.com/domain",
            "items1": [{
                "or": "false",
                "link": "https://wanwang.aliyun.com/domain/com",
                "half": "true",
                "spm": "wwymcom",
                "tce_rule_count": "1",
                "h3": ".com"
            }, {
                "or": "false",
                "link": "https://wanwang.aliyun.com/domain/newgtld/?#.xin",
                "half": "true",
                "spm": "wwymxin",
                "tce_rule_count": "1",
                "h3": ".xin"
            }, {
                "or": "false",
                "link": "https://wanwang.aliyun.com/domain/cn/",
                "half": "true",
                "spm": "wwymcn",
                "tce_rule_count": "1",
                "h3": ".cn"
            }, {
                "or": "false",
                "link": "https://wanwang.aliyun.com/domain/newgtld/?spm=5176.8061372.1001.29.QgL5qZ#.shop",
                "half": "true",
                "spm": "shopyuming",
                "tce_rule_count": "1",
                "h3": ".shop"
            }, {
                "or": "false",
                "link": "https://wanwang.aliyun.com/domain/net",
                "half": "true",
                "spm": "wwymnet",
                "tce_rule_count": "1",
                "h3": ".net"
            }, {
                "or": "false",
                "link": "https://wanwang.aliyun.com/domain/newgtld/#.ltd",
                "half": "true",
                "tce_rule_count": "1",
                "h3": ".ltd"
            }],
            "tce_rule_count": "1"
        }, {
            "or1": "false",
            "or2": "true",
            "title1": "域名交易与转入",
            "spm2": "wwwagnzhjiansh",
            "link2": "https://market.aliyun.com/jianzhan",
            "spm1": "wwyumingzhuanru",
            "title2": "网站建设",
            "items2": [{
                "or": "true",
                "link": "https://market.aliyun.com/tpldns",
                "half": "false",
                "spm": "wwmkmodel",
                "tce_rule_count": "1",
                "h3": "模版建站"
            }, {
                "or": "true",
                "link": "https://market.aliyun.com/products/52738005",
                "half": "false",
                "spm": "wwmkqiyesite",
                "tce_rule_count": "1",
                "h3": "企业官网"
            }, {
                "or": "true",
                "link": "https://market.aliyun.com/products/52750001/",
                "half": "false",
                "spm": "wwmkdssite",
                "tce_rule_count": "1",
                "h3": "商城网站"
            }],
            "link1": "https://mi.aliyun.com",
            "items1": [{
                "or": "false",
                "link": "https://mi.aliyun.com",
                "half": "false",
                "spm": "wwymingtrad",
                "tce_rule_count": "1",
                "h3": "域名交易"
            }, {
                "or": "false",
                "link": "https://wanwang.aliyun.com/domain/yuding#eyJzb3J0VHlwZSI6MX0=",
                "half": "false",
                "spm": "wwyuding",
                "tce_rule_count": "1",
                "h3": "域名预订"
            }, {
                "or": "false",
                "link": "https://wanwang.aliyun.com/domain/transfers",
                "half": "false",
                "spm": "wwymingzhr",
                "tce_rule_count": "1",
                "h3": "域名转入"
            }],
            "tce_rule_count": "1"
        }, {
            "or1": "false",
            "or2": "false",
            "title1": "域名解析",
            "spm2": "wwalimail",
            "link2": "https://wanwang.aliyun.com/mail",
            "spm1": "wwyumingjiexi",
            "title2": "阿里邮箱",
            "items2": [{
                "or": "false",
                "link": "https://wanwang.aliyun.com/mail/",
                "half": "false",
                "spm": "wwqymail",
                "tce_rule_count": "1",
                "h3": "企业邮箱"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/product/directmail",
                "half": "false",
                "spm": "wwmailtui",
                "tce_rule_count": "1",
                "h3": "邮件推送"
            }],
            "link1": "https://wanwang.aliyun.com/domain/dns",
            "items1": [{
                "or": "false",
                "link": "https://wanwang.aliyun.com/domain/dns/",
                "half": "false",
                "spm": "wwdns",
                "tce_rule_count": "1",
                "h3": "云解析DNS"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/product/httpdns",
                "half": "false",
                "spm": "wwHTTPDNS",
                "tce_rule_count": "1",
                "h3": "移动解析HTTPDNS"
            }],
            "tce_rule_count": "1"
        }], "key": "product_network"
    }],
    "tpl5": [{
        "items": [{
            "title": "通用解决方案",
            "items": [{
                "or": "false",
                "link": "https://www.aliyun.com/solution/web",
                "spm": "wangzhsolution",
                "tce_rule_count": "1",
                "h3": "网站解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/app",
                "spm": "yidongAPPsolution",
                "tce_rule_count": "1",
                "h3": "移动APP解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/dedicatedcloud",
                "spm": "zhuanyouyunsolution",
                "tce_rule_count": "1",
                "h3": "专有云解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/hcloud",
                "spm": "hcloudsolution",
                "tce_rule_count": "1",
                "h3": "混合云解决方案"
            }],
            "or": "false",
            "spm": "tongyongsolution",
            "tce_rule_count": "1"
        }, {
            "title": "行业解决方案",
            "items": [{
                "or": "false",
                "link": "https://www.aliyun.com/solution/ecommerce",
                "spm": "dianshangsolution",
                "tce_rule_count": "1",
                "tips": "new",
                "h3": "电商解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/finance",
                "spm": "jinrongsolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "金融解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/healthcare",
                "spm": "yiliaosolution",
                "tce_rule_count": "1",
                "tips": "new",
                "h3": "医疗解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/rendering",
                "spm": "xuanransolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "渲染解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/o2o",
                "spm": "O2Osolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "O2O解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/energy",
                "spm": "nengyuanyunsolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "能源云解决方案"
            }],
            "or": "false",
            "spm": "hangyesolution",
            "tce_rule_count": "1"
        }, {
            "title": "&nbsp;",
            "items": [{
                "or": "false",
                "link": "https://www.aliyun.com/solution/media",
                "spm": "solumedia",
                "tce_rule_count": "1",
                "tips": "new",
                "h3": "音视频解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/game",
                "spm": "solugame",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "游戏解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/govcloud",
                "spm": "solugovsl",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "政务解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/iot",
                "spm": "soluiotsl",
                "tce_rule_count": "1",
                "tips": "new",
                "h3": "物联网解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/genomics/",
                "spm": "solugenomics",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "生物基因解决方案"
            }],
            "or": "false",
            "tce_rule_count": "1"
        }, {
            "title": "专项解决方案",
            "items": [{
                "or": "false",
                "link": "https://www.aliyun.com/solution/security",
                "spm": "anquansolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "安全解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/storage",
                "spm": "yuncunchusolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云存储解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/recovery",
                "spm": "rongzaisolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "容灾解决方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/middleware",
                "spm": "qiyejiagousolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "企业互联网架构方案"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/solution/adn",
                "spm": "yingyongjiaofu",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "应用交付网络解决方案"
            }, {
                "or": "false",
                "link": "https://data.aliyun.com/solution/dispatch",
                "spm": "dispatch",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "智能配送调度解决方案"
            }, {
                "or": "false",
                "link": "https://data.aliyun.com/solution/vr",
                "spm": "vrsolution",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "VR应用开发解决方案"
            }],
            "or": "false",
            "spm": "zhuanxiangsolution",
            "tce_rule_count": "1"
        }, {
            "title": "大数据解决方案",
            "items": [{
                "or": "false",
                "p": "根据用户的兴趣特点和购买行为进行推荐",
                "link": "https://data.aliyun.com/solution/re",
                "spm": "solugxhtuij",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "个性化推荐"
            }, {
                "or": "false",
                "p": "从数据采集、加工，到运维调度等完整的数仓解决方案",
                "link": "https://data.aliyun.com/solution/base",
                "spm": "solubigdata",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "大数据仓库"
            }, {
                "or": "false",
                "p": "跨异构存储系统的数据传输交互服务",
                "link": "https://data.aliyun.com/solution/cdp",
                "spm": "solu_yundatajic",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "云上数据集成方案"
            }, {
                "or": "false",
                "p": "实时预判的路况预测系统",
                "link": "https://data.aliyun.com/solution/rp",
                "spm": "soluroadpre",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "路况预测"
            }, {
                "or": "false",
                "p": "构建基于企业全息画像和企业关系网络的企业级服务",
                "link": "https://data.aliyun.com/solution/cds",
                "spm": "soluqiyedatafw",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "企业级数据服务解决方案"
            }, {
                "or": "false",
                "p": "提供实时台风路径分析预报等服务",
                "link": "https://data.aliyun.com/visual/tiqas",
                "spm": "solutaifeng",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "台风路径分析"
            }, {
                "or": "false",
                "p": "助您快速搭建自有营销推广系统",
                "link": "https://data.aliyun.com/solution/dm",
                "spm": "shuziyinxiao",
                "tce_rule_count": "1",
                "tips": "new",
                "h3": "数字营销解决方案"
            }, {
                "or": "false",
                "p": "为工业客户提供基于人工智能的解决方案",
                "link": "https://data.aliyun.com/solution/industry",
                "spm": "gongyedashuju",
                "tce_rule_count": "1",
                "tips": "new",
                "h3": "工业大数据服务解决方案"
            }],
            "or": "false",
            "spm": "bigdatasolution",
            "tce_rule_count": "1"
        }], "key": "solution"
    }, {
        "items": [{
            "title": "支持计划",
            "items": [{
                "or": "false",
                "link": "https://www.aliyun.com/support/techsupport",
                "spm": "fuwushouhoufw",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "售后支持计划"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/support/service/list",
                "spm": "fuwuzxiangfw",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "尊享服务"
            }, {
                "or": "false",
                "link": "https://www.aliyun.com/support/quyu",
                "spm": "fuwuareafw",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "区域服务"
            }],
            "or": "false",
            "tce_rule_count": "1"
        }, {
            "title": "帮助与文档",
            "items": [{
                "or": "false",
                "link": "https://help.aliyun.com",
                "spm": "zhichidochelp",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "文档与常见问题"
            }, {
                "or": "false",
                "link": "https://help.aliyun.com/contact/school.htm",
                "spm": "xinshouxuetang",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "新手学堂"
            }, {
                "or": "false",
                "link": "https://help.aliyun.com/contact/service.htm",
                "spm": "zhichigongju",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "支持工具"
            }],
            "or": "false",
            "link": "https://help.aliyun.com",
            "spm": "sphelpndoc",
            "tce_rule_count": "1"
        }, {
            "title": "资源",
            "items": [{
                "or": "false",
                "link": "https://develop.aliyun.com/api",
                "spm": "docapid",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "API"
            }, {
                "or": "false",
                "link": "https://develop.aliyun.com/sdk/java",
                "spm": "docsdkd",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "SDK"
            }, {
                "or": "false",
                "link": "https://develop.aliyun.com/command/cli",
                "spm": "docdevtoold",
                "tce_rule_count": "1",
                "tips": "none",
                "h3": "开发者工具"
            }],
            "or": "false",
            "tce_rule_count": "1"
        }], "key": "support"
    }],
    "$tmsId": "429638"
}